import Head from "next/head";
import { Inter } from "@next/font/google";

import { use, useEffect, useRef, useState } from "react";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

const { Configuration, OpenAIApi } = require("openai");
const configuration = new Configuration({
  apiKey: "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",
});
const openai = new OpenAIApi(configuration);

export default function Home() {
  const [data, setData] = useState(null);
  const inputRef = useRef(null);
  const router = useRouter();
  useEffect(() => {
    router.push("/login");
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>{/* <Login /> */}</div>
      </main>
    </>
  );
}
