import Head from "next/head";
import { Inter } from "@next/font/google";
import Login from "@/components/login";
import { useRef, useState } from "react";
import { tryApi } from "@/helpers/generateData";

const inter = Inter({ subsets: ["latin"] });

const { Configuration, OpenAIApi } = require("openai");
const configuration = new Configuration({
  apiKey: "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",
});
const openai = new OpenAIApi(configuration);

export default function Home() {
  const [data, setData] = useState(null);
  const inputRef = useRef(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <button onClick={tryApi}>Try</button>
          <Login />

          <input type="text" ref={inputRef} />
          <button
            onClick={() => {
              tryApi(inputRef.current.value, setData);
            }}
          >
            Submit
          </button>
          {data && <p>{data}</p>}
        </div>
      </main>
    </>
  );
}
