import Head from "next/head";
import { Inter } from "@next/font/google";
import Login from "@/components/login";

const inter = Inter({ subsets: ["latin"] });

const { Configuration, OpenAIApi } = require("openai");
const configuration = new Configuration({
  apiKey: "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",
});
const openai = new OpenAIApi(configuration);

const tryApi = async () => {
  const requestOptions = {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization:
        "Bearer " +
        String("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"),
    },
    body: JSON.stringify({
      prompt:
        "Generate a problem statement for the phrase 'E-commerce website for plants ' max 90 words.",
      temperature: 0.1,
      max_tokens: 100,
      top_p: 1,
      frequency_penalty: 0,
      presence_penalty: 0.5,
      stop: ['"""'],
    }),
  };
  fetch(
    "https://api.openai.com/v1/engines/text-davinci-003/completions",
    requestOptions
  )
    .then((response) => response.json())
    .then((data) => {
      // # Do something with data
      console.log(data);
    })
    .catch((err) => {
      console.log("Ran out of tokens for today! Try tomorrow!");
    });
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={tryApi}>Try</button>
        <Login />
      </main>
    </>
  );
}
